### ISSUE TITLE
Helm Chart: Version upgrade for new OpenJ9 releases

### ISSUE THREAD

**Issue by chrisc66** [eclipse/openj9-utils#46]
The JITServer helm chart version needs to follow every OpenJ9 release to include the latest Adopt release images. This issue keeps track of changes that need to be applied to the helm chart. 

There are three files that require updates for every version upgrade. 
- `values.yaml`
- `Chart.yaml`
- `index.yaml`

**Comment by chrisc66** [comment]
This comment summarizes the changes need to be applied to `values.yaml`. 

Using version upgrade from 0.24 to 0.25 as an example. This file contains the image repository and tag that the helm chart pulls and deploys. The image tag needs to match the latest OpenJ9 release image on [Adopt Docker Hub](https://hub.docker.com/_/adoptopenjdk?tab=tags&page=1&ordering=last_updated).

- Old version is using 0.24 image tag
``` yaml
image:
  repository: adoptopenjdk
  tag: 8u282-b08-jdk-openj9-0.24.0
  pullPolicy: Always
```

- Update to 0.25 image tag
``` yaml
image:
  repository: adoptopenjdk
  tag: 0.25_IMAGE_TAG
  pullPolicy: Always
```
